export enum MessageRole {
  USER = 'user',
  ASSISTANT = 'assistant'
}

export enum MessageType {
  TEXT = 'text',
  FIGMA_CARD = 'figma_card',
  IMAGE = 'image',
  AUDIO = 'audio'
}

export interface ExecutionStep {
  type: 'thought' | 'tool_call' | 'action' | 'handoff';
  content: string;
}

export interface Message {
  id: string;
  role: MessageRole;
  content: string;
  type: MessageType;
  timestamp: number;
  imageUrl?: string; // Optional field for image data (base64)
  audioData?: string; // Optional field for audio data (base64)
  agentName?: string; // Optional field to display which agent generated the message
  action?: {
    label: string;
    url: string;
  };
  trace?: ExecutionStep[];
}

export interface ChatSession {
  id: string;
  title: string;
  date: string; // e.g., 'Today', 'Yesterday'
  preview: string;
}

export interface Symptom {
  description: string;
  duration: string;
  severity: string; // e.g., "Mild", "Moderate", "Severe" or 1-10
  notes?: string;
}

export interface MemoryBank {
  chiefComplaint: string;
  symptomTimeline: Symptom[];
  currentMedications: string[];
  familyHistory: string[];
  suggestedQuestions: string[]; // Generated by Agent B
}