import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { MemoryBank } from '@/types';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  subtitle: {
    fontSize: 10,
    color: '#6B7280',
    marginTop: 4,
  },
  userInfo: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  userName: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#374151',
  },
  date: {
    fontSize: 10,
    color: '#9CA3AF',
    marginTop: 2,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  card: {
    backgroundColor: '#F9FAFB',
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  mainText: {
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 1.5,
  },
  timelineItem: {
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  timelineItemLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  timelineTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  tagContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  tag: {
    fontSize: 9,
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    color: '#4B5563',
  },
  grid: {
    flexDirection: 'row',
    gap: 20,
  },
  column: {
    flex: 1,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 6,
    alignItems: 'center',
  },
  bullet: {
    width: 4,
    height: 4,
    backgroundColor: '#9CA3AF',
    borderRadius: 2,
    marginRight: 8,
  },
  listText: {
    fontSize: 11,
    color: '#374151',
  },
  questionItem: {
    flexDirection: 'row',
    marginBottom: 8,
    backgroundColor: '#F9FAFB',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  questionNumber: {
    width: 20,
    fontSize: 10,
    fontWeight: 'bold',
    color: '#6B7280',
  },
  questionText: {
    flex: 1,
    fontSize: 11,
    color: '#1F2937',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  footerText: {
    fontSize: 8,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
});

interface ReportPDFProps {
  data: MemoryBank;
  userName: string;
  date: string;
}

export const ReportPDF: React.FC<ReportPDFProps> = ({ data, userName, date }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Doctor Briefing</Text>
          <Text style={styles.subtitle}>Generated by Prepped AI Agent</Text>
        </View>
        <View style={styles.userInfo}>
          <Text style={styles.userName}>{userName}</Text>
          <Text style={styles.date}>{date}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Chief Complaint</Text>
        <View style={styles.card}>
          <Text style={styles.mainText}>"{data.chiefComplaint}"</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Symptom Timeline</Text>
        <View style={styles.card}>
          {data.symptomTimeline.map((item, idx) => (
            <View key={idx} style={[styles.timelineItem, idx === data.symptomTimeline.length - 1 ? styles.timelineItemLast : {}]}>
              <Text style={styles.timelineTitle}>{item.description}</Text>
              <View style={styles.tagContainer}>
                <Text style={styles.tag}>{item.duration}</Text>
                <Text style={styles.tag}>Severity: {item.severity}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>

      <View style={[styles.section, styles.grid]}>
        <View style={styles.column}>
          <Text style={styles.sectionTitle}>Current Medications</Text>
          <View style={styles.card}>
            {data.currentMedications.length > 0 ? (
              data.currentMedications.map((med, idx) => (
                <View key={idx} style={styles.listItem}>
                  <View style={styles.bullet} />
                  <Text style={styles.listText}>{med}</Text>
                </View>
              ))
            ) : (
              <Text style={[styles.listText, { fontStyle: 'italic', color: '#9CA3AF' }]}>None recorded</Text>
            )}
          </View>
        </View>

        <View style={styles.column}>
          <Text style={styles.sectionTitle}>Family History</Text>
          <View style={styles.card}>
            {data.familyHistory.length > 0 ? (
              data.familyHistory.map((item, idx) => (
                <View key={idx} style={styles.listItem}>
                  <View style={styles.bullet} />
                  <Text style={styles.listText}>{item}</Text>
                </View>
              ))
            ) : (
              <Text style={[styles.listText, { fontStyle: 'italic', color: '#9CA3AF' }]}>None recorded</Text>
            )}
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Suggested Questions</Text>
        {data.suggestedQuestions.map((q, idx) => (
          <View key={idx} style={styles.questionItem}>
            <Text style={styles.questionNumber}>{idx + 1}</Text>
            <Text style={styles.questionText}>{q}</Text>
          </View>
        ))}
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Confidential • Generated by AI • Not Medical Advice</Text>
      </View>

    </Page>
  </Document>
);
